// This handler answers every request, including requests for plain files, so it
// can do two things a file server cannot: pick a representation based on the
// Accept header, and set headers on the way out. serve.mjs runs it.
//
// IMPORTANT: every header the site sends is set here, and there is no second
// place to look. Whatever proxy sits in front terminates TLS and must add no headers.

// The facts the handler cannot work out for itself, generated by build.mjs from
// the pages it actually built: the canonical host, and which routes are written
// for a person. That file is gitignored and rewritten on every build, and
// serve.mjs refuses to start without it -- so a skipped build is a loud error
// rather than a silently stale list, the point of generating it.
import { CANONICAL_HOST, HUMAN_ROUTES, SITE_ORIGIN } from "./routes.generated.ts";
import {
  CONTENT_TYPE, HOLD, cached, canonicalPath, handle, heldSeconds, matchRoute, matchSitemapChild,
  negotiate, pagePath, privateView, robotsFor,
} from "./spaces.ts";
import { SIGN_IN_PAGE, handleSignedIn, isSignedInAddress } from "./me.ts";
import type { ApiEnv } from "./api.ts";
import { LINK_CODE, NAME, SEQ } from "./grammar.ts";

interface Env extends ApiEnv {
  /** The files the build wrote to public/, by literal path, with ETags. A path
   *  with no such file is a plain 404, which this handler turns into the page. */
  ASSETS: { fetch(request: Request): Promise<Response> };
}

// The one list of what a built file is. serve.mjs hands over bytes and an ETag
// and nothing else; the type of every response is decided here.
const EXT_TYPE: Record<string, string> = {
  ".md": "text/markdown; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".svg": "image/svg+xml; charset=utf-8",
  ".png": "image/png",
  ".woff2": "font/woff2",
};

// Agent pages load nothing at all: no script, no font, no image. The policy
// says so out loud, and the only relaxation is the inline CSS and the empty
// data: favicon in the head.
const CSP_STRICT =
  "default-src 'none'; style-src 'unsafe-inline'; img-src data:; " +
  "base-uri 'none'; form-action 'none'; frame-ancestors 'none'";

// A page written for a person loads this origin's self-hosted font and SVG
// logos. Still same-origin only -- 'self' never
// permits a third party. Applying CSP_STRICT here would silently break the page.
const CSP_PAGE =
  "default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; " +
  "img-src 'self' data:; font-src 'self'; " +
  "base-uri 'none'; form-action 'none'; frame-ancestors 'none'";

// The dynamic pages under /spaces and /inspect load nothing either -- no font,
// no script, no image -- so they are as locked down as an agent page, with one
// difference: the directory has a search box, and `form-action 'none'` stops a
// form submitting at all, including a GET one. 'self' permits this origin and
// nowhere else.
const CSP_DYNAMIC =
  "default-src 'none'; style-src 'unsafe-inline'; img-src data:; " +
  "base-uri 'none'; form-action 'self'; frame-ancestors 'none'";

// The sign-in page, and it alone: the passkey prompt is JavaScript, and it asks
// this site for a challenge and hands it the passkey's answer. So its own script,
// and requests to this origin and nowhere else. Every other signed-in page is forms
// under CSP_DYNAMIC, which permits no script and no request, except the two below.
const CSP_SIGN_IN =
  "default-src 'none'; style-src 'unsafe-inline'; img-src data:; script-src 'self'; connect-src 'self'; " +
  "base-uri 'none'; form-action 'self'; frame-ancestors 'none'";

// This site's own script and no request of any kind: the policy of every signed-in page
// that runs a script of its own, except the sign-in page. Each of the four names below
// is this one policy, for its pages, so a change to it reaches all of them.
const CSP_OWN_SCRIPT =
  "default-src 'none'; style-src 'unsafe-inline'; img-src data:; script-src 'self'; " +
  "base-uri 'none'; form-action 'self'; frame-ancestors 'none'";

// The signed-in pages that carry a post form, a space's, a post's and an oracle space's
// history: a person's passkey signs a post in the browser, which is JavaScript. So this
// site's own script, and still no request of any kind: the script reads the form, asks
// the passkey, and fills the form, which the browser then submits as any form.
const CSP_SIGN_POST = CSP_OWN_SCRIPT;
// Every address matchSignedInRoute() answers with the HTML of those three pages, where a
// passkey signs a post, a proposal, an approval, a decline or an undo:
// trailing slashes and .html included. Under the policy for plain forms the post
// form would render there with its script blocked, and a ticked "Sign it" would
// post the post unsigned without a word.
const SIGN_POST_PAGE = new RegExp(`^/me/spaces/${NAME}(/${SEQ}|/history)?/*(\\.html)?$`);

// The pages whose one-click buttons count only a press made on purpose, and no request of
// any kind: /me/connect, where a person answers an app (Allow); an invite link's signed-in
// page (Join, Take over); and the mailbox, which carries offers of a role (Accept). Their
// script, src/allow.js, keeps each such button switched off until the page has been in
// front for most of a second. A double click another site steers onto the button is the
// attack it stops, and framing, the older one, is refused here as everywhere. A space's
// own page carries Accept too, and runs the same script under CSP_SIGN_POST. And the page
// of keys blocked from posting in a space (Let it post again), with the answer to a key
// typed there in no key's shape, which is that page again. /me/connect also runs
// src/connect-signing.js and the module it imports, /connection-key.js, when an app may
// write: it makes the key the app signs posts with in Web Crypto and asks the passkey to
// allow it, which needs this site's own script and nothing more, and its answer goes with
// the Allow form, so still no request of any kind and no change to the policy.
const CSP_PRESS = CSP_OWN_SCRIPT;
const PRESS_PAGE = new RegExp(`^/me/(connect|mailbox|join/${NAME}/${LINK_CODE}/*|spaces/${NAME}/blocks?)$`);

// The page where a person makes an access token for an agent or a program,
// /me/tokens/new: its own script, which asks the passkey the session connected with to
// confirm, and no request of any kind. The challenge is drawn into the page, so the
// script needs no connect-src.
const CSP_NEW_TOKEN = CSP_OWN_SCRIPT;
const NEW_TOKEN_PAGE = "/me/tokens/new";

// The pages where a person's own browser seals and opens, src/sealed-page.js: the key's
// page, with its sealing panel; a new space, which may be sealed; a sealed space's
// keepers' page; and the direct messages, where a pair may be sealed. This site's own
// script and no request of any kind, as for signing a post: the script reads the page,
// keeps the person's encryption key in the browser and fills the forms, which the
// browser then submits as any form. A sealed space's own pages and its posts' are
// covered above, under CSP_SIGN_POST, which is the same policy.
const CSP_SEALED = CSP_OWN_SCRIPT;
const SEALED_PAGE = new RegExp(
  `^/me(/new|/spaces/${NAME}/keepers|/messages(/new|/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?)?/*(\\.html)?$`,
);

// Which routes get the relaxed policy. Not a list kept here -- a rule, applied to
// whatever build.mjs generated. A list here would make every new page for a person a
// code change that nobody would remember to make, and the symptom of forgetting is a
// page that renders without its font or its logos and says nothing about why.
const HUMAN = new Set(HUMAN_ROUTES);

/** Whether the page at a built file's base path, "/index" for the homepage, is
 *  written for a person. */
const forPerson = (base: string) => HUMAN.has(base === "/index" ? "/" : base);

// Two years, and preload, matching the HSTS policy the API sends, so the two hosts
// state the same policy. Only ever sent over HTTPS: RFC 6797 forbids it on a
// non-secure response, which is also why the smoke test only asserts it against an
// https origin.
const HSTS = "max-age=63072000; includeSubDomains; preload";

function decorate(
  res: Response,
  opts: {
    type?: string;
    alternates?: { md: string; json: string };
    csp?: string;
    secure?: boolean;
    /** Overrides the default "index, follow". /inspect is read with a key that
     *  has real memberships and must never reach a search index. */
    robots?: string;
    /** Overrides must-revalidate for a page that may be held in a cache. */
    cacheControl?: string;
    /** The address this page declares as its own. Sent as a Link header so it
     *  survives being served from a cache, and so the markdown and JSON
     *  representations carry it too -- they have no <head> to put it in. */
    canonical?: string;
    /** Overrides "no-referrer", for the signed-in pages only. See where it is set. */
    referrer?: string;
  },
): Response {
  // A 304 arrives with no body, as a Response with that status must.
  const out = new Response(res.body, res);

  const h = out.headers;
  if (opts.type) h.set("Content-Type", opts.type);

  // Accept changes which representation is returned, so caches must key on it.
  // Without this, a cache can hand markdown to a browser and HTML to an agent.
  h.set("Vary", "Accept");

  // One Link header, built once: a second h.set() would overwrite the first rather
  // than append to it.
  const links: string[] = [];
  if (opts.alternates) {
    // rel="alternate" is standard (RFC 8288). rel="llms-txt" is not registered
    // anywhere -- it is a vendor convention, included because it is free and
    // some agents look for it.
    links.push(`<${opts.alternates.md}>; rel="alternate"; type="text/markdown"`);
    links.push(`<${opts.alternates.json}>; rel="alternate"; type="application/json"`);
    links.push(`</llms.txt>; rel="llms-txt"`);
  }
  // Omitted on anything marked noindex: declaring a canonical for a page you
  // have just told a crawler not to list is contradictory signalling.
  if (opts.canonical) links.push(`<${opts.canonical}>; rel="canonical"`);
  if (links.length) h.set("Link", links.join(", "));

  h.set("Cache-Control", opts.cacheControl ?? "public, max-age=0, must-revalidate");
  h.set("X-Robots-Tag", opts.robots ?? "index, follow, max-snippet:-1");
  h.set("Content-Security-Policy", opts.csp ?? CSP_STRICT);
  h.set("X-Content-Type-Options", "nosniff");
  h.set("Referrer-Policy", opts.referrer ?? "no-referrer");
  if (opts.secure) h.set("Strict-Transport-Security", HSTS);
  return out;
}

/** Seconds left of a page's lifetime. A copy from the page cache carries the Age
 *  it was held for, and is handed on with what remains; a fresh render has no
 *  Age and gets all of it. Re-stamping every copy with the full lifetime would
 *  send a page held four minutes of ten out with ten more. The Age header is
 *  dropped once it has been subtracted, or a client that honours it would take
 *  it off a second time. */
function lifetimeLeft(res: Response, seconds: number): number {
  const age = Number(res.headers.get("Age")) || 0;
  res.headers.delete("Age");
  return Math.max(0, seconds - age);
}

/** The answer to one request. serve.mjs calls this and nothing else. */
export async function handleRequest(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const path = url.pathname;
  const secure = url.protocol === "https:";

  // ONE canonical host, decided before anything is served. Every canonical URL,
  // every sitemap line and every llms.txt entry names the apex, so a site that
  // also answers on www is two sites to a crawler and splits its own indexing.
  // Only the exact www name is redirected: localhost, and any preview host, are
  // left alone so the site can be run and tested anywhere.
  if (url.hostname === `www.${CANONICAL_HOST}`) {
    // An invite link's address carries its code, and so do the signed-in one it leads to
    // and /sign-in?next= between them: their redirect is kept by no cache, as they are.
    const credential = /^\/(join|me|sign-in)(\/|$)/.test(path);
    return new Response(null, {
      status: 301,
      headers: {
        Location: `https://${CANONICAL_HOST}${path}${url.search}`,
        "Cache-Control": credential ? "private, no-store" : "public, max-age=3600",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "no-referrer",
        ...(secure ? { "Strict-Transport-Security": HSTS } : {}),
      },
    });
  }

  // THE SIGNED-IN PAGES, before every other route, and THE ONLY ADDRESSES THAT
  // TAKE A POST. They decide who is reading from the session and never from the
  // address alone, so nothing they send may be stored by any cache or listed by
  // any search engine, whatever it contains -- the sign-in page included, which
  // says whether somebody is signed in.
  if (isSignedInAddress(path)) {
    // Set by serve.mjs from the connection or the proxy, never by the visitor:
    // serve.mjs overwrites whatever a request sent under this name.
    const client = request.headers.get("x-schellingaf-client");
    const res = await handleSignedIn(request, url, env, secure, client);
    return decorate(res, {
      csp: path === SIGN_IN_PAGE ? CSP_SIGN_IN
        : SIGN_POST_PAGE.test(path) ? CSP_SIGN_POST
        : PRESS_PAGE.test(path) ? CSP_PRESS
        : path === NEW_TOKEN_PAGE ? CSP_NEW_TOKEN
        : SEALED_PAGE.test(path) ? CSP_SEALED
        : CSP_DYNAMIC,
      secure,
      robots: "noindex, nofollow",
      cacheControl: "private, no-store",
      // NOT no-referrer, on these pages alone. Under a no-referrer policy a
      // browser sends "Origin: null" with every form it submits (the Fetch
      // standard, "append a request Origin header"), so the Origin check every
      // signed-in form must pass would refuse every form, Sign out included.
      // same-origin keeps the real origin on this site's own requests and still
      // sends no referrer to anybody else.
      referrer: "same-origin",
    });
  }
  // Every other address on this site is read, never written to. serve.mjs lets a
  // POST through for the family above, and this refuses it everywhere else before
  // a single read of the product: a POST skips the page cache, so it would be an
  // uncached read of the API that anybody could repeat.
  if (request.method !== "GET" && request.method !== "HEAD") {
    return decorate(new Response("405 Method Not Allowed: this address is read with GET.\n", {
      status: 405,
      headers: { Allow: "GET, HEAD" },
    }), { type: "text/plain; charset=utf-8", secure, robots: "noindex, nofollow", cacheControl: "no-store" });
  }

  // The dynamic routes, before anything is looked for on disk. They are not
  // files: /spaces and /inspect are rendered here from the product's JSON.
  // Everything else on this site is a file the build produced.
  // The space sitemap children, and the categories' one, are matched here too, because
  // they carry a file extension: the branch below hands anything with an extension to
  // the asset server, which has no such file and would answer 404.
  //
  // A search is asked only by a q with something in it. An empty or blank one is
  // the directory: readParams() keeps no such q, so the two share one page-cache
  // entry and must be one page.
  const asksSearch = (url.searchParams.get("q") ?? "").trim() !== "";
  const route = matchSitemapChild(path) ?? matchRoute(path, request.headers.get("Accept"), env, asksSearch);
  if (route) {
    const page = pagePath(route);
    const res = await cached(route, url, () => handle(route, url, env));
    // A page that asks to be held for less than its route's lifetime is, here as in the
    // page cache; the header that says so is this site's own and does not leave it.
    const maxAge = heldSeconds(route, res);
    res.headers.delete(HOLD);
    const left = lifetimeLeft(res, maxAge);
    // A page that did not render is not a page. A 503 outage notice or a 404
    // must not be held for five minutes -- a held 503 outlives the outage that
    // caused it while its own Retry-After says sixty seconds -- and neither goes
    // to crawlers under "index, follow", which invites a search engine to list
    // an error.
    const good = res.status === 200;
    // A page may know it must not be listed where its route cannot: a space
    // that is closed or withheld is decided by what the service answered, not
    // by the address. It says so on its own response, and that is kept here —
    // including on a cached copy, which is why it rides on the response rather
    // than on the route.
    const pageNoindex = /noindex/i.test(res.headers.get("X-Robots-Tag") ?? "");
    // The same decision the page wrote into its own head. See robotsFor.
    const robots = robotsFor(route, res.status, pageNoindex);
    return decorate(res, {
      // A sitemap child is XML, with no markdown or JSON twin to advertise.
      alternates: route.kind === "sitemap" || route.kind === "category-sitemap" ? undefined : { md: `${page}.md`, json: `${page}.json` },
      csp: CSP_DYNAMIC,
      secure,
      canonical: robots.startsWith("index") ? SITE_ORIGIN + canonicalPath(route, url) : undefined,
      robots,
      // Rendered with a key that has real memberships: out of every shared cache
      // including the browser's. See privateView for why that is decided by the key.
      cacheControl: privateView(route)
        ? "private, no-store"
        : res.status === 301
          // A permanent redirect points at an address that never changes: a post's
          // id at its number, the facet root at the directory.
          ? "public, max-age=86400"
          : !good
            ? "no-store"
            : maxAge > 0
              ? `public, max-age=${left}, stale-while-revalidate=60`
              : undefined,
    });
  }

  const get = (assetPath: string) =>
    env.ASSETS.fetch(new Request(new URL(assetPath, url), request));

  // THE NOT-FOUND PAGE IS NOT AN ADDRESS. The build writes it as a file so that
  // notFound() has something to serve. Asked for by name it must not answer 200 under
  // "index, follow", nor advertise a markdown and a JSON twin that do not exist.
  if (path === "/404.html" || path.replace(/\/+$/, "") === "/404") return notFound(env, url, secure);

  // A path with a file extension is served as-is: /index.md, /llms.txt,
  // /robots.txt, /sitemap.xml and the .json siblings all land here.
  const ext = path.match(/\.[a-z0-9]+$/i);
  if (ext) {
    const res = await get(path);
    if (res.status === 404) return notFound(env, url, secure);
    // A designed page is also reachable at its own .html, because that is the
    // file the asset server holds. Served with the strict policy it renders
    // without its font, its logos or its script and says nothing about why, so
    // the same rule that decides the policy for "/api" decides it for
    // "/api.html".
    const suffix = ext[0].toLowerCase();
    return decorate(res, {
      type: EXT_TYPE[suffix],
      csp: suffix === ".html" && forPerson(path.slice(0, -5)) ? CSP_PAGE : CSP_STRICT,
      secure,
    });
  }

  // Otherwise it is a page route. "/" maps to /index.*, "/api" to /api.*,
  // "/docs/foo" to /docs/foo.* -- so pages added later need no code change.
  const base = path === "/" ? "/index" : path.replace(/\/+$/, "");
  const format = negotiate(request.headers.get("Accept"));

  const res = await get(`${base}.${format}`);
  if (res.status === 404) return notFound(env, url, secure);

  return decorate(res, {
    type: CONTENT_TYPE[format],
    alternates: { md: `${base}.md`, json: `${base}.json` },
    // Only the HTML of a page written for a person needs the relaxed policy. Its
    // markdown and JSON representations load nothing, so they keep the strict one.
    csp: format === "html" && forPerson(base) ? CSP_PAGE : CSP_STRICT,
    secure,
  });
}

async function notFound(env: Env, url: URL, secure: boolean): Promise<Response> {
  // Read without the visitor's own headers. With them, If-None-Match: * or the ETag
  // of an earlier 404 makes the file server answer 304, which would go out as a 404
  // with an empty body.
  const res = await env.ASSETS.fetch(new Request(new URL("/404.html", url)));
  // What robotsFor says of a live page that did not render.
  const out = decorate(res, { type: EXT_TYPE[".html"], secure, robots: "noindex, nofollow" });
  return new Response(out.body, { status: 404, headers: out.headers });
}
